### ISSUE TITLE
GUI: Create basic React app with NEAR layout and deploy to GH Pages

### ISSUE THREAD

**Issue by zahhar** [epam/near-nftchecker#1]
NEAR layout to follow: https://explorer.near.org/
Deployment pipeline to GH pages - using Parcel, Yarn (see Corgis FE stack)
Using JS API 0.40 - https://github.com/near/near-api-js/

Main area: 
- Title "NEAR NFT Checker"
- 2 text inputs - "NFT Contract Address" (mandatory) and "Token ID" (optional) 
- "Check it" button.

**Comment by sxurik** [comment]
Finished in #11 and #12. The current version of the checker is available on https://epam.github.io/near-nftchecker/
